version: '3'

services:

  fogbus2-federated_learning1:
    # image: fogbus2-naive_formula0
    image: fogbus2-federated_learning1
    platform: linux/x86_64
    build:
      context: ../../
      dockerfile: dockerFiles/FederatedServer/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode:
      host
